Parameters:
  DirectoryId:
    Type: String
    Description: Enter Diretory ID
  DnsServer1:
    Type: String
    Description: Enter DNS Server
  DnsServer2:
    Type: String
    Description: Enter DNS Server
  ServerCertificateArn:
    Type: String
    Description: Enter Server Certificate ARN
  TargetNetwork:
    Type: String
    Description: Enter "grw-vpn-sb-az-a" Subnet id
Resources:
  GRWClientVpnEndpoint:
    Type: AWS::EC2::ClientVpnEndpoint
    Properties:
      AuthenticationOptions:
        - Type: "directory-service-authentication"
          ActiveDirectory:
            DirectoryId: !Ref DirectoryId
      ClientCidrBlock: "172.16.0.0/16"
      ConnectionLogOptions:
        Enabled: false
      Description: "GRW Client VPN Endpoint"
      DnsServers:
        - !Ref DnsServer1
        - !Ref DnsServer2 # Use DnsServer2 instead of DnsServer1 here
      ServerCertificateArn: !Ref ServerCertificateArn
      TagSpecifications:
        - ResourceType: "client-vpn-endpoint"
          Tags:
            - Key: "Name"
              Value: "gre-vpn-ep"
      TransportProtocol: "udp"

  GRWClientVpnTargetNetworkAssociation:
    Type: "AWS::EC2::ClientVpnTargetNetworkAssociation"
    Properties:
      ClientVpnEndpointId: !Ref GRWClientVpnEndpoint
      SubnetId: !Ref TargetNetwork
