AWSTemplateFormatVersion: '2010-09-09'
Description: Builing step 2 for Global Remote Work

Parameters:
  GRWPrivateSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Select grw-pri-sb-az-a, grw-pri-sb-az-c

  GRWVpcId:
    Type: AWS::EC2::VPC::Id
    Description: Select grw-vpc

Resources:
  GRWDirectory:
    Type: AWS::DirectoryService::MicrosoftAD
    Properties:
      Name: "lundaljung.com"
      Password: "p@ssw0rd"
      ShortName: "CloudStudy"
      Edition: Standard
      VpcSettings:
        SubnetIds: !Ref GRWPrivateSubnetIds
        VpcId: !Ref GRWVpcId