AWSTemplateFormatVersion: '2010-09-09'
Description: Builing step 4 - Create AWS WorkSpace

Parameters:
  Bundle:
    Type: String
    Description: Select the bundle that should be deployed
  Directory:
    Type: String
    Description: Enter the Directory ID for the WorkSpace (Directory Services or AD Connector)
  User:
    Type: String
    Description: Enter the username who will use the WorkSpace
    AllowedPattern: ^[a-z0-9]{1,20}$
    ConstraintDescription: user must be entered using lower case letters and numbers and a maximum of 20 characters 
  
Resources:
  GRWWorkSpace:
    Type: AWS::WorkSpaces::Workspace
    Properties:
      BundleId: !Ref Bundle
      DirectoryId: !Ref Directory
      UserName: !Ref User
      RootVolumeEncryptionEnabled: false
      UserVolumeEncryptionEnabled: false
      WorkspaceProperties:
        RunningMode: "AUTO_STOP"